function init()
  connect(g_game, { onGameEnd = onGameEnd })
  connect(g_game, 'onTextMessage', onArena)
  
  kardWindow = g_ui.displayUI('voc')
  Escolher = kardWindow:recursiveGetChildById('Escolher')
  HP = kardWindow:recursiveGetChildById('hp')
  MP = kardWindow:recursiveGetChildById('mp')
  Cap = kardWindow:recursiveGetChildById('cap')
  Reg = kardWindow:recursiveGetChildById('reg')
  Escolher:disable()
  HP:hide()
  MP:hide()
  Cap:hide()
  Reg:hide()
  kardWindow:hide()
end

function Tanker()
	Interface = kardWindow:recursiveGetChildById('vocInterface')
	VocInfor = kardWindow:recursiveGetChildById('infoVoc')
	SkillUm = kardWindow:recursiveGetChildById('skillUm')
	SkillUmInfo = kardWindow:recursiveGetChildById('infoUm')
	SkillDois = kardWindow:recursiveGetChildById('skillDois')
	SkillDoisInfo = kardWindow:recursiveGetChildById('infoDois')
	SkillTres = kardWindow:recursiveGetChildById('skillTres')
	SkillTresInfo = kardWindow:recursiveGetChildById('infoTres')
	SkillQuatro = kardWindow:recursiveGetChildById('skillQuatro')
	SkillQuatroInfo = kardWindow:recursiveGetChildById('infoQuatro')
	SkillCinco = kardWindow:recursiveGetChildById('skillCinco')
	SkillCincoInfo = kardWindow:recursiveGetChildById('infoCinco')
	
	Interface:setImageSource('img/Tanker')
	VocInfor:setText('+ Maior HP | + Pouco Dano em habilidades. | + Destreza ++\n\nAtributo em destaque: • Vitalidade | • Capacidade | • Destreza.')
	SkillUm:setImageSource('img/15-15-15')
	SkillUmInfo:setText('Invencível a dano por 10 segundos.')
	SkillDois:setImageSource('img/3-3-3')
	SkillDoisInfo:setText('Ataque em área do tipo FIRE.')
	SkillTres:setImageSource('img/4-4-4')
	SkillTresInfo:setText('Ataque em área do tipo HOLY.')
	SkillQuatro:setImageSource('img/5-5-5')
	SkillQuatroInfo:setText('Ataque em área do tipo ICE.')
	SkillCinco:setImageSource('img/14-14-14')
	SkillCincoInfo:setText('Provoca um inimigo até você.')
	HP:show()
	MP:show()
	Cap:show()
	Reg:show()
	HP:setText('09')
	MP:setText('06')
	Cap:setText('09')
	Reg:setText('02')
	Escolher:enable()
	Escolher.onClick = function() g_game.talk("!SkillAdd VocTanker") kardWindow:hide() end
end
function Especialista()
	Interface = kardWindow:recursiveGetChildById('vocInterface')
	VocInfor = kardWindow:recursiveGetChildById('infoVoc')
	SkillUm = kardWindow:recursiveGetChildById('skillUm')
	SkillUmInfo = kardWindow:recursiveGetChildById('infoUm')
	SkillDois = kardWindow:recursiveGetChildById('skillDois')
	SkillDoisInfo = kardWindow:recursiveGetChildById('infoDois')
	SkillTres = kardWindow:recursiveGetChildById('skillTres')
	SkillTresInfo = kardWindow:recursiveGetChildById('infoTres')
	SkillQuatro = kardWindow:recursiveGetChildById('skillQuatro')
	SkillQuatroInfo = kardWindow:recursiveGetChildById('infoQuatro')
	SkillCinco = kardWindow:recursiveGetChildById('skillCinco')
	SkillCincoInfo = kardWindow:recursiveGetChildById('infoCinco')
	
	Interface:setImageSource('img/Especialista')
	VocInfor:setText('+ HP/MP médios | + Dano em habilidade equilibrado. | + Destreza - | + Boa capacidade.\n\nAtributo em destaque: • Capacidade | • Vitalidade | • Espiritualidade.')
	SkillUm:setImageSource('img/28-28-28')
	SkillUmInfo:setText('Empurra o inimigo.')
	SkillDois:setImageSource('img/29-29-29')
	SkillDoisInfo:setText('Paraliza o inimigo por alguns segundos.')
	SkillTres:setImageSource('img/16-16-16')
	SkillTresInfo:setText('Ataque em área do tipo DEATH.')
	SkillQuatro:setImageSource('img/17-17-17')
	SkillQuatroInfo:setText('Ataque em área do tipo POISON.')
	SkillCinco:setImageSource('img/30-30-30')
	SkillCincoInfo:setText('Reflete parte do dano recebido por alguns segundos.')
	HP:show()
	MP:show()
	Cap:show()
	Reg:show()
	HP:setText('08')
	MP:setText('07')
	Cap:setText('08')
	Reg:setText('01')
	Escolher:enable()
	Escolher.onClick = function() g_game.talk("!SkillAdd VocEspecialista") kardWindow:hide() end
end
function Curandeiro()
	Interface = kardWindow:recursiveGetChildById('vocInterface')
	VocInfor = kardWindow:recursiveGetChildById('infoVoc')
	SkillUm = kardWindow:recursiveGetChildById('skillUm')
	SkillUmInfo = kardWindow:recursiveGetChildById('infoUm')
	SkillDois = kardWindow:recursiveGetChildById('skillDois')
	SkillDoisInfo = kardWindow:recursiveGetChildById('infoDois')
	SkillTres = kardWindow:recursiveGetChildById('skillTres')
	SkillTresInfo = kardWindow:recursiveGetChildById('infoTres')
	SkillQuatro = kardWindow:recursiveGetChildById('skillQuatro')
	SkillQuatroInfo = kardWindow:recursiveGetChildById('infoQuatro')
	SkillCinco = kardWindow:recursiveGetChildById('skillCinco')
	SkillCincoInfo = kardWindow:recursiveGetChildById('infoCinco')
	
	Interface:setImageSource('img/Curandeiro')
	VocInfor:setText('+ Habilidades de Cura | + Maior MP | + Maior Dano em habilidades | + Destreza --\n\nAtributo em destaque: • Espiritualidade | • Potência | • Experiência.')
	SkillUm:setImageSource('img/21-21-21')
	SkillUmInfo:setText('Cura um amigo próximo.')
	SkillDois:setImageSource('img/22-22-22')
	SkillDoisInfo:setText('Cura vários jogadores dentro da área de execução.')
	SkillTres:setImageSource('img/23-23-23')
	SkillTresInfo:setText('Acelera a regeneração de HP por alguns segundos.')
	SkillQuatro:setImageSource('img/26-26-26')
	SkillQuatroInfo:setText('Ataque em área do tipo ENERGY.')
	SkillCinco:setImageSource('img/27-27-27')
	SkillCincoInfo:setText('Acelera a regeneração de SP por alguns segundos.')
	HP:show()
	MP:show()
	Cap:show()
	Reg:show()
	HP:setText('06')
	MP:setText('09')
	Cap:setText('06')
	Reg:setText('03')
	Escolher:enable()
	Escolher.onClick = function() g_game.talk("!SkillAdd VocCurandeiro") kardWindow:hide() end
end

function onArena(mode, text)
	if not g_game.isOnline() then
		return
	end
	if mode == MessageModes.Failure then
		if string.find(text, "OpenedWindowVoc") then
		  kardWindow:show()
		  kardWindow:raise()
		  kardWindow:focus()
		  addEvent(function() g_effects.fadeIn(kardWindow, 250) end)
		end
	end
end

function terminate()
  disconnect(g_game, { onGameEnd = onGameEnd })
  disconnect(g_game, 'onTextMessage', onArena)

  kardWindow:destroy()
end

function onGameEnd()
  if kardWindow:isVisible() then
    kardWindow:hide()
  end
end

function show()
    kardWindow:show()
    kardWindow:raise()
    kardWindow:focus()
    Interface = kardWindow:recursiveGetChildById('vocInterface')
	VocInfor = kardWindow:recursiveGetChildById('infoVoc')
	SkillUm = kardWindow:recursiveGetChildById('skillUm')
	SkillUmInfo = kardWindow:recursiveGetChildById('infoUm')
	SkillDois = kardWindow:recursiveGetChildById('skillDois')
	SkillDoisInfo = kardWindow:recursiveGetChildById('infoDois')
	SkillTres = kardWindow:recursiveGetChildById('skillTres')
	SkillTresInfo = kardWindow:recursiveGetChildById('infoTres')
	SkillQuatro = kardWindow:recursiveGetChildById('skillQuatro')
	SkillQuatroInfo = kardWindow:recursiveGetChildById('infoQuatro')
	SkillCinco = kardWindow:recursiveGetChildById('skillCinco')
	SkillCincoInfo = kardWindow:recursiveGetChildById('infoCinco')
	Escolher = kardWindow:recursiveGetChildById('Escolher')
	HP = kardWindow:recursiveGetChildById('hp')
	MP = kardWindow:recursiveGetChildById('mp')
	Cap = kardWindow:recursiveGetChildById('cap')
	Reg = kardWindow:recursiveGetChildById('reg')
    addEvent(function() g_effects.fadeIn(kardWindow, 250) end)
	Escolher:disable()
	Interface:setImageSource('img/00')
	VocInfor:setText(' ')
	SkillUm:setImageSource('img/0')
	SkillUmInfo:setText(' ')
	SkillDois:setImageSource('img/0')
	SkillDoisInfo:setText(' ')
	SkillTres:setImageSource('img/0')
	SkillTresInfo:setText(' ')
	SkillQuatro:setImageSource('img/0')
	SkillQuatroInfo:setText(' ')
	SkillCinco:setImageSource('img/0')
	SkillCincoInfo:setText(' ')
	HP:hide()
	MP:hide()
	Cap:hide()
	Reg:hide()
end

function hide()
  addEvent(function() g_effects.fadeOut(kardWindow, 250) end)
  scheduleEvent(function() kardWindow:hide() end, 250)
end

function toggle()
  if kardWindow:isVisible() then
    hide()
  else
    show()
  end
end